name: Ubuntu CPU Build & Test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #TODO: does this do anything?
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install CUDA
      env:
        cuda: "11.2"
      run: |
        source ./scripts/installation/install_cuda_ubuntu.sh
        if [[ $? -eq 0 ]]; then
          # Set paths for subsequent steps, using ${CUDA_PATH}
          echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
          echo "CUDA_PATH=${CUDA_PATH}" >> $GITHUB_ENV
          echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install OpenGL
      run: |
        source ./scripts/installation/install_open_gl_ubuntu.sh
      shell: bash

    - name: Build
      shell: bash
      run: ./compile.sh

    - name: Test CPU
      env:
        SIMULATION_USE_GPU: "false"
      shell: bash
      run: ./test.sh -nc

    - name: Run CPU
      env:
        SIMULATION_USE_GPU: "false"
      shell: bash
      run: ./engine.sh -n